Story.create(title: "Once a upon", creator: "Alan")
Story.create(title: "Hello world", creator: "Dennis")
Story.create(title: "Tech Web", creator: "Bob")

Image.create(number: 1)
Image.create(number: 2)
Image.create(number: 3)
Image.create(number: 4)
Image.create(number: 5)
Image.create(number: 6)
Image.create(number: 7)
Image.create(number: 8)
Image.create(number: 9)
Image.create(number: 10)
Image.create(number: 11)
Image.create(number: 12)
Image.create(number: 13)
Image.create(number: 14)
Image.create(number: 15)
Image.create(number: 16)
Image.create(number: 17)
Image.create(number: 18)
Image.create(number: 19)
Image.create(number: 20)
